on:
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Setup git
        run: |
          git config --global user.name 'Github Action'
          git config --global user.email 'github-action@users.noreply.github.com'

      - name: Switch to main
        run: cd public && git checkout main && cd ../

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.147.9'
          extended: true

      - name: Install NPM
        run: npm i

      - name: Build
        run: hugo --minify

      - name: Deploy
        run: cd public && git add . && git commit --allow-empty -m 'Release ${{github.run_number}}' && git push

#      - name: Deploy
#        uses: peaceiris/actions-gh-pages@v3
#        if: github.ref == 'refs/heads/main'
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./public

